<?php

namespace Finance\BackOfficeBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

use Doctrine\ORM\EntityRepository;

/**
 * ClientPhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientPhysiqueRepository extends EntityRepository
{
	
	public function findClientsStartWith($start_with)
	{
		
		$qb = $this->createQueryBuilder('c')
				->orWhere('c.nom like :start')
				->orWhere('c.prenom like :start')
				->orWhere('c.ncin like :start')
				->orWhere('c.nPasseport like :start')
				->setParameter('start', $start_with.'%')
				->getQuery();
		
		return $qb->execute();
	}
	
	public function findGerantStartWith($start_with)
	{
		$list_gerant = $this->
		_em->
		createQuery("SELECT cl.id FROM FinanceBackOfficeBundle:ClientMoral c Join c.gerant cl ")
		->execute();
		
		$query = $this->_em->createQuery(
				"Select c FROM FinanceBackOfficeBundle:ClientPhysique c WHERE c.id not in (:list)".
				"and ( c.nom like :start  or  c.prenom like :start or c.ncin like :start or c.nPasseport like :start )"
				)->setParameter("list", $list_gerant)->setParameter("start", $start_with."%");
		
	
		return $query->execute();
	}
	
}
