<?php

namespace Finance\BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientMoralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientMoralRepository extends EntityRepository
{
	
	
	
}
