<?php

namespace Finance\BackOfficeBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
	
	
	public function getNotificationsByComptes($comptes,$type)
	{
		$ids = array();
		foreach($comptes as $c)
		{
			$ids[] = $c->getId();
		}
		
		$qb = $this->createQueryBuilder('n')->where('n.type = :type')->setParameter('type', $type);
		$qb->join('n.compte', 'c',Join::WITH,'c.id in (:list)')->setParameter('list', $ids);
		return $qb->getQuery()->execute();
	}
}
