#services:
#    clientrepository:
#        class: Finance\BackOfficeBundle\Repository\ClientRepository
#        arguments: ["@doctrine.orm.entity_manager"]
services:
    tokenValidatorService:
        class: Finance\BackOfficeBundle\Services\ValidateRestTokenService
        arguments: ["@doctrine.orm.entity_manager","@request_stack"]
